sonar.projectKey=jpeg-rs
sonar.projectName=jpeg-rs

sonar.sources=jpeg-core/src,jpeg-io/src,jpeg-cli/src

sonar.tests=jpeg-core/tests,jpeg-cli/tests

sonar.sourceEncoding=UTF-8

sonar.language=rust
sonar.rust.lcov.reportPaths=lcov.info
sonar.rust.clippy.reportPaths=clippy-report.json
sonar.sarifReportPaths=cargo-audit.sarif